version: '3'

tasks:
  setup:
    desc: Install dependencies
    cmds:
      - go mod download

  build:
    desc: Build the CLI executable
    cmds:
      - go build -o ./bin/nutc-analyzer

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  lint:
    desc: Run Go linter
    cmds:
      - go fmt ./...
      - go vet ./...

  run:
    desc: Run the CLI tool
    cmds:
      - task: build
      - ./bin/nutc-analyzer

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf ./bin/

  all:
    desc: Run all tasks
    cmds:
      - task: setup
      - task: lint
      - task: test
      - task: build
      - task: run

